# Generated by Django 2.1.2 on 2018-10-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='IsActive',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='IsDeleted',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='landline',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='website',
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
    ]
