# Generated by Django 2.1 on 2018-10-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0002_job_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
