# Generated by Django 2.1 on 2018-10-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0003_identity_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('country', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('zipcode', models.CharField(max_length=120)),
                ('fulladdress', models.CharField(max_length=120)),
                ('latitude', models.CharField(max_length=120)),
                ('longitude', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('profileViews', models.BooleanField(default=True)),
                ('newMessage', models.BooleanField(default=True)),
                ('newfavourite', models.BooleanField(default=True)),
                ('jobStatus', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='age',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='location',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='salary',
        ),
        migrations.AddField(
            model_name='seeker',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='emailIsVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seeker',
            name='enableTwoStepVerification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seeker',
            name='facebookIsVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seeker',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='phoneIsVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seeker',
            name='profileImage',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='seeker', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='securityAnswer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='securityQuestion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='takingJob',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobhunt.Address'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobhunt.Notification'),
        ),
    ]
