# Generated by Django 2.1.2 on 2018-10-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0003_auto_20181027_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
