# Generated by Django 2.1 on 2018-11-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0004_auto_20181030_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='dribbble',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='git',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='pintrest',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='youtube',
        ),
    ]
