# Generated by Django 2.1 on 2018-11-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0006_auto_20181101_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='is_provider',
            new_name='is_user',
        ),
        migrations.RenameField(
            model_name='identity',
            old_name='is_seeker',
            new_name='is_worker',
        ),
    ]
